name: CI

on:
  push:
    branches: [master,main]
  pull_request:
    branches: [master,main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v5

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: k2db
          environment-file: environment.yml
          miniforge-version: latest
          channels: conda-forge,bioconda
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true

      - name: Run BATS suite
        run: bats -T --abort test/test.sh

